### ISSUE TITLE
Array out of range when retrieving IPs

### ISSUE THREAD

**Issue by saShenka-dev** [GigaXCodes/NoIP-Updater-IPv6#1]
There seems to be an issue with retrieving the IP adresses, at least on my machine.
I always get an exception for an array being out of range.

https://imgur.com/a/jhJcSD5

**Comment by GigaXCodes** [comment]
This seemed to occour if you had set your own link local addresses.
Thanks for your issue, i've fixed it with the recent commit.

Checkout Version v1.0.1 for fixed Version: [GigaXCodes/NoIP-Updater-IPv6/releases/tag/v1.0.1](https://github.com/GigaXCodes/NoIP-Updater-IPv6/releases/tag/v1.0.1)
